<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>GameScripts</AssemblyName>
    <RootNamespace>SRP2D</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/engine/scripting/CSharp/Prisma.Core/Prisma.Core.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="../../../../src/engine/scripting/CSharp/Prisma.Generators/Prisma.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <TrimmerRootAssembly Include="GameScripts" />
  </ItemGroup>
</Project>
