using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace PrismaEngine.Generators
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public class PrismaDiagnosticSuppressor : DiagnosticSuppressor
    {
        private static readonly SuppressionDescriptor CS0260Suppression = new SuppressionDescriptor(
            id: "PRISMA_S001",
            suppressedDiagnosticId: "CS0260",
            justification: "Prisma handles partial class generation and provides a more specific diagnostic (PRISMA001).");

        private static readonly SuppressionDescriptor CS0534Suppression = new SuppressionDescriptor(
            id: "PRISMA_S002",
            suppressedDiagnosticId: "CS0534",
            justification: "Prisma Source Generator will implement the abstract members in the other partial part.");

        public override ImmutableArray<SuppressionDescriptor> SupportedSuppressions => 
            ImmutableArray.Create(CS0260Suppression, CS0534Suppression);

        public override void ReportSuppressions(SuppressionAnalysisContext context)
        {
            foreach (var diagnostic in context.ReportedDiagnostics)
            {
                if (diagnostic.Id == "CS0260" || diagnostic.Id == "CS0534")
                {
                    var location = diagnostic.Location;
                    var syntaxTree = location.SourceTree;
                    if (syntaxTree == null) continue;

                    var root = syntaxTree.GetRoot(context.CancellationToken);
                    var node = root.FindNode(location.SourceSpan);
                    var classDeclaration = node.AncestorsAndSelf().OfType<ClassDeclarationSyntax>().FirstOrDefault();
                    if (classDeclaration == null) continue;

                    // 获取语义模型以检查符号 / Get semantic model to check symbol
                    var model = context.GetSemanticModel(syntaxTree);
                    var symbol = model.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                    if (symbol == null) continue;

                    // 核心逻辑：只有当该类的其它部分是在我们的生成器中生成的，才进行压制
                    // Core logic: Only suppress if other parts of this class are generated by our generator
                    bool hasPrismaGeneratedPart = symbol.DeclaringSyntaxReferences.Any(r => 
                        r.SyntaxTree.FilePath.Contains("PrismaEngine.Generators") || 
                        r.SyntaxTree.FilePath.EndsWith(".g.cs"));

                    if (hasPrismaGeneratedPart)
                    {
                        if (diagnostic.Id == "CS0260")
                            context.ReportSuppression(Suppression.Create(CS0260Suppression, diagnostic));
                        else
                            context.ReportSuppression(Suppression.Create(CS0534Suppression, diagnostic));
                    }
                }
            }
        }
    }
}
