#pragma once

#define PRISMA_ENABLE_AUDIO_SDL3 1
#define PRISMA_ENABLE_AUDIO_3D 1
#define PRISMA_ENABLE_AUDIO_STREAMING 1
#define PRISMA_ENABLE_AUDIO_HRTF 0

#define PRISMA_ENABLE_AUDIO_DSP 1
#define PRISMA_ENABLE_AUDIO_MINIAUDIO 1
#define PRISMA_ENABLE_AUDIO_SYNTHESIZER 1
#define PRISMA_ENABLE_AUDIO_EFFECTS 1
#define PRISMA_ENABLE_AUDIO_RAYTRACING 0
#define PRISMA_ENABLE_AUDIO_CODEC_OGG 1
#define PRISMA_ENABLE_AUDIO_CODEC_MP3 1
#define PRISMA_ENABLE_AUDIO_CODEC_FLAC 1
