#pragma once

#include "AudioBackendConfig.h"
#include "RenderBackendConfig.h"

#define PRISMA_ENGINE_NAME "Prisma Engine"
#define PRISMA_ENGINE_VERSION_MAJOR 0
#define PRISMA_ENGINE_VERSION_MINOR 1
#define PRISMA_ENGINE_VERSION_PATCH 0

#ifdef _DEBUG
#define PRISMA_BUILD_TYPE "Debug"
#define PRISMA_LOG_LEVEL 4
#define PRISMA_ENABLE_MEMORY_TRACKING 1
#define PRISMA_ENABLE_RESOURCE_HOT_RELOAD 1
#define PRISMA_ENABLE_PROFILER 1
#define PRISMA_ENABLE_DEBUG_DRAW 1
#else
#define PRISMA_BUILD_TYPE "Release"
#define PRISMA_LOG_LEVEL 3
#define PRISMA_ENABLE_MEMORY_TRACKING 0
#define PRISMA_ENABLE_RESOURCE_HOT_RELOAD 0
#define PRISMA_ENABLE_PROFILER 0
#define PRISMA_ENABLE_DEBUG_DRAW 0
#endif

#define PRISMA_ENGINE_CONFIG_STRING \
    PRISMA_ENGINE_NAME " v" \
    PRISMA_STRINGIFY(PRISMA_ENGINE_VERSION_MAJOR) "." \
    PRISMA_STRINGIFY(PRISMA_ENGINE_VERSION_MINOR) "." \
    PRISMA_STRINGIFY(PRISMA_ENGINE_VERSION_PATCH) \
    " (" PRISMA_BUILD_TYPE ")"

#define PRISMA_LOG_LEVEL_TRACE 5
#define PRISMA_LOG_LEVEL_DEBUG 4
#define PRISMA_LOG_LEVEL_INFO  3
#define PRISMA_LOG_LEVEL_WARN  2
#define PRISMA_LOG_LEVEL_ERROR 1
#define PRISMA_LOG_LEVEL_FATAL 0

#define PRISMA_ENABLE_LOGGING 1
#define PRISMA_ENABLE_MEMORY_POOL 1
#define PRISMA_POOL_SIZE (64 * 1024 * 1024)
#define PRISMA_ENABLE_MULTITHREADING 1
#define PRISMA_MAX_WORKER_THREADS 8
#define PRISMA_ENABLE_PHYSICS 1
#define PRISMA_PHYSICS_BACKEND "Bullet"
#define PRISMA_ENABLE_NETWORKING 1
#define PRISMA_ENABLE_CLIENT_SERVER 1
#define PRISMA_ENABLE_P2P 0
#define PRISMA_ENABLE_SCRIPTING 1
#define PRISMA_SCRIPT_LANGUAGE "Lua"
#define PRISMA_ENABLE_ASYNC_LOADING 1
#define PRISMA_ENABLE_RESOURCE_COMPRESSION 1
#define PRISMA_ENABLE_IMGUI 1
#define PRISMA_ENABLE_NUKLEAR 0
#define PRISMA_ENABLE_BENCHMARK 0

#define PRISMA_STRINGIFY(x) #x
#define PRISMA_STRINGIZE2(x) PRISMA_STRINGIFY(x)

#define PRISMA_PLATFORM_WINDOWS
#define PRISMA_ARCH_X64
#define PRISMA_COMPILER_MSVC
#define PRISMA_COMPILER_VERSION _MSC_VER

#define PRISMA_STATIC_ASSERT(condition, message) static_assert(condition, message)
#define PRISMA_DEPRECATED __declspec(deprecated)
#define PRISMA_FORCE_INLINE __forceinline
#define PRISMA_ALIGN(size) __attribute__((aligned(size)))
#define PRISMA_API
#define PRISMA_LOCAL
