using System;
using System.Runtime.InteropServices;
using Prisma;

namespace GameScripts;

/// <summary>
/// C++ 引擎通过 CoreCLR 调用的入口点�?
/// </summary>
internal static class ScriptEntry
{
    [UnmanagedCallersOnly]
    public static void Bootstrap(IntPtr apiPtr)
    {
        ScriptEngine.Bootstrap(apiPtr);

        // 注册所有源码生成的脚本
        // Register all scripts generated by source generator
        GameScripts.Generated.ScriptRegistry.RegisterAll();

        // 创建场景 �?SceneInit 会创建摄像机 + 精灵
        var init = Node.Create("__SceneInit__");
        init.AddScript<SceneInit>();

        System.Console.WriteLine("[GameScripts] Scene initialized");
    }

    [UnmanagedCallersOnly]
    public static void OnFrame(float dt)
    {
        ScriptEngine.OnFrame(dt);
    }
}
