# GitHub Actions 工作流：Release 时自动构建并上传 APK
# 当创建新的 Git Tag 时触发

name: Release Build

on:
  push:
    tags:
      - 'v*'  # 匹配 v1.0, v2.3.4 等标签
  workflow_dispatch:

jobs:
  release:
    name: 构建发布版本
    runs-on: ubuntu-latest

    steps:
      # ============ 1. 检出代码 ============
      - name: 检出代码
        uses: actions/checkout@v4

      # ============ 2. 设置 JDK ============
      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ============ 3. 缓存 NDK 和 Gradle ============
      - name: 缓存 Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-

      - name: 缓存 NDK
        uses: actions/cache@v4
        with:
          path: |
            ~/Android/Sdk/ndk
            ~/.android/build-cache
          key: ndk-${{ runner.os }}-${{ hashFiles('**/build.gradle*') }}
          restore-keys: ndk-${{ runner.os }}-

      # ============ 4. 授予执行权限 ============
      - name: 授予执行权限
        run: chmod +x ./gradlew

      # ============ 5. 读取版本信息 ============
      - name: 获取版本号
        id: get_version
        run: |
          # 从 Git Tag 获取版本号
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_ENV

      # ============ 6. 配置签名（可选）============
      # 如果需要签名 Release APK，取消下面的注释并配置密钥
      # 需要在 GitHub Secrets 中添加：
      # - KEYSTORE_FILE: Base64 编码的 keystore 文件
      # - KEYSTORE_PASSWORD: keystore 密码
      # - KEY_ALIAS: 密钥别名
      # - KEY_PASSWORD: 密钥密码
      #
      # - name: 解密签名密钥
      #   if: env.KEYSTORE_FILE != ''
      #   run: |
      #     echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > release.keystore
      #
      # - name: 创建 keystore 属性文件
      #   if: env.KEYSTORE_FILE != ''
      #   run: |
      #     cat << EOF > keystore.properties
      #     storeFile=release.keystore
      #     storePassword=${{ secrets.KEYSTORE_PASSWORD }}
      #     keyAlias=${{ secrets.KEY_ALIAS }}
      #     keyPassword=${{ secrets.KEY_PASSWORD }}
      #     EOF

      # ============ 7. 构建 Release APK ============
      - name: 构建 Release APK
        run: ./gradlew assembleRelease --build-cache --stacktrace

      # ============ 8. 重命名 APK ============
      - name: 重命名 APK
        run: |
          mkdir -p release
          cp app/build/outputs/apk/release/*.apk release/PrismaAndroid-v${VERSION}-release.apk 2>/dev/null || \
          find app/build/outputs/apk/release -name "*.apk" -exec cp {} release/PrismaAndroid-v${VERSION}-release.apk \;

      # ============ 9. 创建 GitHub Release ============
      - name: 创建 Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: release/*.apk
          generate_release_notes: true  # 自动生成更新日志
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ============ 10. 上传构建产物 ============
      - name: 上传 APK 到 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-v${{ steps.get_version.outputs.VERSION }}
          path: release/*.apk
          retention-days: 90
