#pragma once

#include "math/MathTypes.h"
#include "Export.h"
#include <vector>
#include <cstdint>

namespace Prisma::Water {

/**
 * @brief A single ripple instance generated by water interaction
 */
struct Ripple {
    Vector3 center;       // world position of impact
    float startRadius;    // initial radius (typically 0)
    float currentRadius;  // expanding radius
    float maxRadius;      // max radius before fade
    float amplitude;      // ripple height
    float lifetime;       // total lifetime
    float age;            // current age

    bool IsAlive() const { return age < lifetime && amplitude > 0.001f; }
    float GetNormalizedAge() const { return lifetime > 0.0f ? age / lifetime : 1.0f; }
    float GetFade() const { return 1.0f - GetNormalizedAge(); }
};

/**
 * @brief WaterInteraction - generates ripples when objects interact with water
 * 
 * Manages a pool of ripples. When a physics body enters water bounds,
 * a ripple is spawned at the intersection point. Each ripple is an
 * expanding ring displacement on the water surface that fades over time.
 */
class ENGINE_API WaterInteraction {
public:
    WaterInteraction() = default;
    ~WaterInteraction() = default;

    /**
     * @brief Spawn a ripple at world position
     * @param position  impact world position
     * @param strength  impact strength (affects amplitude)
     * @param maxRadius maximum radius in meters
     * @param lifetime  duration in seconds
     */
    void SpawnRipple(const Vector3& position,
                     float strength = 1.0f,
                     float maxRadius = 10.0f,
                     float lifetime = 4.0f);

    /**
     * @brief Update all ripples
     * @param deltaTime  time since last update
     * @param rippleSpeed  ripple expansion speed (m/s)
     * @param decayRate  amplitude decay rate
     */
    void Update(float deltaTime, float rippleSpeed, float decayRate);

    /**
     * @brief Get ripple displacement at world position
     * @param worldPos  world XZ position
     * @return height displacement contributed by all active ripples
     */
    float GetDisplacement(const Vector2& worldPos) const;

    /**
     * @brief Clear all ripples
     */
    void Clear();

    /**
     * @brief Set maximum number of concurrent ripples
     */
    void SetMaxRipples(uint32_t maxRipples) { m_MaxRipples = maxRipples; }

    /**
     * @brief Get active ripple count
     */
    size_t GetActiveCount() const { return m_Ripples.size(); }

    /**
     * @brief Get all ripples (for debugging / GPU upload)
     */
    const std::vector<Ripple>& GetRipples() const { return m_Ripples; }

private:
    std::vector<Ripple> m_Ripples;
    uint32_t m_MaxRipples = 64;
};

} // namespace Prisma::Water
