#pragma once

#define PRISMA_ENABLE_RENDER_VULKAN 1
#define PRISMA_ENABLE_RASTERIZATION 1
#define PRISMA_ENABLE_RAYTRACING 0
#define PRISMA_ENABLE_MESH_SHADERS 0
#define PRISMA_ENABLE_VARIABLE_RATE_SHADING 0
#define PRISMA_ENABLE_COMPUTE_SHADERS 1
#define PRISMA_ENABLE_GEOMETRY_SHADERS 1
#define PRISMA_ENABLE_TESSELLATION_SHADERS 1
#define PRISMA_ENABLE_MULTITHREADED_RENDERING 1
#define PRISMA_ENABLE_BINDLESS_RESOURCES 0
#define PRISMA_ENABLE_ASYNC_COMPUTE 0
#define PRISMA_ENABLE_GBUFFER 1
#define PRISMA_ENABLE_HDR 1
#define PRISMA_ENABLE_TONEMAPPING 1
#define PRISMA_ENABLE_BLOOM 1
#define PRISMA_ENABLE_SSR 0
#define PRISMA_ENABLE_SSGI 0
#define PRISMA_RENDER_USE_PIX 1
#define PRISMA_RENDER_USE_GPU_VALIDATION 1
#define PRISMA_VULKAN_REQUIRED_VERSION_MAJOR 1
#define PRISMA_VULKAN_REQUIRED_VERSION_MINOR 3
